import Head from 'next/head';
import Layout, { siteTitle } from '../components/layout'
import styles from '../styles/Home.module.css';

function Home({stories, pageNumber}) {
  return (
    <Layout home>
      <Head>
        <title>{siteTitle}</title>
      </Head>
      <section className={styles.headingMd}>
        <h1 className={styles.title}>
          Welcome to <a href="">AI.Stories!</a>
        </h1>

        <p className={styles.description}>
          Funny stories generated by GPT-3 and other AI models
        </p>
      </section>
    </Layout>
  )
}

// This function gets called at build time on server-side.
// It won't be called on client-side, so you can even do
// direct database queries.
export async function getStaticProps() {
  // Call an external API endpoint to get posts.
  // You can use any data fetching library
  const res = await fetch('')
  const stories = await res.json()

  // By returning { props: { posts } }, the Blog component
  // will receive `posts` as a prop at build time
  return {
    stories: {
      stories["Stories"],
    },
  }
}

export default Home